name: Code QA

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci --prefer-offline

      - run: npm run lint
      - run: npm run typecheck
