name: Publish Site

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 7,8,9,10 * * 1-5'

defaults:
  run:
    shell: bash

jobs:
  github-pages:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      pages: write
      contents: read
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - name: Cache scrapes in case of temporary failures
        uses: actions/cache@v5
        with:
          key: menus-${{ github.run_id }}
          restore-keys: |
            menus-${{ github.run_id }}
            menus-
          path: |
            _site/assets
            _site/restaurants.json
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci --prefer-offline

      - name: Setup Pages
        uses: actions/configure-pages@v6
      - run: npm run scrape
      - run: |
          SHA="$(git rev-parse --short HEAD)"
          sed -i "s/version: dev/version: $SHA/g" _site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
